// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    partial class TravelApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Travel", b =>
                {
                    b.Property<int>("TravelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("TravelId");

                    b.ToTable("Travels");

                    b.HasData(
                        new
                        {
                            TravelId = 1,
                            City = "Siem Reap",
                            Country = "Cambodia",
                            Date = new DateTime(2009, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Angkor Wat",
                            Rating = 7,
                            Review = "Spiritual"
                        },
                        new
                        {
                            TravelId = 2,
                            City = "Beijing",
                            Country = "China",
                            Date = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Great Wall",
                            Rating = 9,
                            Review = "Great"
                        },
                        new
                        {
                            TravelId = 3,
                            City = "Paris",
                            Country = "France",
                            Date = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Louvre Museum",
                            Rating = 4,
                            Review = "Crowded"
                        },
                        new
                        {
                            TravelId = 4,
                            City = "London",
                            Country = "United Kingdom",
                            Date = new DateTime(2023, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Big Ben",
                            Rating = 9,
                            Review = "Great"
                        },
                        new
                        {
                            TravelId = 5,
                            City = "Beijing",
                            Country = "China",
                            Date = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Summer Palace",
                            Rating = 7,
                            Review = "Good"
                        },
                        new
                        {
                            TravelId = 6,
                            City = "Beijing",
                            Country = "China",
                            Date = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Temple of Heaven",
                            Rating = 8,
                            Review = "Great"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
